[book]
authors = ["thu-tram"]
language = "en"
title = "Thư trạm's guide to vietnamese grammar"
src = "src"

[output.html]
default-theme = "Navy"
additional-css = ["style/custom.css"]
no-section-label = true

[output.html.fold]
enable = true

[output.html.search]
use-boolean-and = true   # multiple search terms combined with AND opposed to OR